# golangci-lint configuration for Typosentinel
# Enhanced configuration for comprehensive code quality checks

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-dirs:
    - vendor
    - temp
    - artifacts
    - reports
    - dist
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"
  uniq-by-line: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  # Error detection
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  # Code complexity
  gocyclo:
    min-complexity: 10

  gocognit:
    min-complexity: 15

  # Function length
  funlen:
    lines: 80
    statements: 40

  # Line length
  lll:
    line-length: 120
    tab-width: 4

  # Naming conventions
  golint:
    min-confidence: 0.8

  # Imports
  goimports:
    local-prefixes: github.com/Alivanroy/Typosentinel

  # Security
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked (we handle this with errcheck)

  # Performance
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  # Code style
  gofmt:
    simplify: true

  gofumpt:
    extra-rules: true

  # Unused code
  unused:
    check-exported: false

  # Ineffective assignments
  ineffassign:
    check-exported: false

  # Misspellings
  misspell:
    locale: US
    ignore-words:
      - typosquatting
      - typosentinel

  # Struct tags
  govet:
    settings:
      printf:
        funcs:
          - (github.com/sirupsen/logrus.FieldLogger).Infof
          - (github.com/sirupsen/logrus.FieldLogger).Warnf
          - (github.com/sirupsen/logrus.FieldLogger).Errorf
          - (github.com/sirupsen/logrus.FieldLogger).Fatalf

  # Whitespace
  whitespace:
    multi-if: false
    multi-func: false

  # Duplicate code
  dupl:
    threshold: 100

  # Magic numbers
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
        ignored-numbers: 0,1,2,3
        ignored-functions: strings.SplitN

  # Nested if statements
  nestif:
    min-complexity: 4

  # Test packages
  testpackage:
    skip-regexp: (export|internal)_test\\.go

  # Exhaustive switch
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false

  # Error wrapping
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(

  # Nil checks
  nilnil:
    checked-types:
      - ptr
      - func
      - iface
      - map
      - chan

linters:
  enable:
    # Error detection
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Code style
    - gofmt
    - gofumpt
    - goimports
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    
    # Complexity
    - gocyclo
    - gocognit
    - funlen
    - nestif
    
    # Security
    - gosec
    
    # Performance
    - prealloc
    - bodyclose
    
    # Bugs
    - rowserrcheck
    - sqlclosecheck
    - nilerr
    - nilnil
    
    # Best practices
    - dupl
    - goconst
    - gocritic
    - godot
    - gomnd
    - misspell
    - nakedret
    - nolintlint
    - exportloopref
    - exhaustive
    - wrapcheck
    
    # Testing
    - testpackage
    - tparallel
    
    # Formatting
    - lll
    
  disable: []

  # Enable all available linters
  # enable-all: true
  # disable:
  #   - linters-to-disable

  # Disable specific linters
  # disable:
  #   - errcheck

  # Enable only specific linters
  # enable:
  #   - megacheck
  #   - govet

  # Enable presets
  # presets:
  #   - bugs
  #   - unused
  #   - complexity
  #   - style
  #   - performance