linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - gosec
    - staticcheck
    - unused
    - ineffassign
    - misspell

linters-settings:
  errcheck:
    exclude-functions:
      - fmt:.*
      - io/ioutil:^Read.*
  gosec:
    severity: medium

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
