# golangci-lint configuration for Typosentinel
# Enhanced configuration for comprehensive code quality checks

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - temp
    - artifacts
    - reports
    - dist
  skip-files:
    - ".*\.pb\.go$"
    - ".*_generated\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  # Error detection
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  # Code complexity
  gocyclo:
    min-complexity: 10

  gocognit:
    min-complexity: 15

  # Function length
  funlen:
    lines: 80
    statements: 40

  # Line length
  lll:
    line-length: 120
    tab-width: 4

  # Naming conventions
  golint:
    min-confidence: 0.8

  # Imports
  goimports:
    local-prefixes: github.com/Alivanroy/Typosentinel

  # Security
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked (we handle this with errcheck)

  # Performance
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  # Code style
  gofmt:
    simplify: true

  gofumpt:
    extra-rules: true

  # Unused code
  unused:
    check-exported: false

  # Ineffective assignments
  ineffassign:
    check-exported: false

  # Misspellings
  misspell:
    locale: US
    ignore-words:
      - typosquatting
      - typosentinel

  # Struct tags
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/sirupsen/logrus.FieldLogger).Infof
          - (github.com/sirupsen/logrus.FieldLogger).Warnf
          - (github.com/sirupsen/logrus.FieldLogger).Errorf
          - (github.com/sirupsen/logrus.FieldLogger).Fatalf

  # Whitespace
  whitespace:
    multi-if: false
    multi-func: false

  # Interface compliance
  interfacer:
    check-exported: true

  # Duplicate code
  dupl:
    threshold: 100

  # Magic numbers
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
        ignored-numbers: 0,1,2,3
        ignored-functions: strings.SplitN

  # Nested if statements
  nestif:
    min-complexity: 4

  # Test packages
  testpackage:
    skip-regexp: (export|internal)_test\.go

  # Exhaustive switch
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false

  # Error wrapping
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(

  # Nil checks
  nilnil:
    checked-types:
      - ptr
      - func
      - iface
      - map
      - chan

linters:
  enable:
    # Error detection
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - deadcode
    - structcheck
    
    # Code style
    - gofmt
    - gofumpt
    - goimports
    - golint
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    
    # Complexity
    - gocyclo
    - gocognit
    - funlen
    - nestif
    
    # Security
    - gosec
    
    # Performance
    - prealloc
    - bodyclose
    
    # Bugs
    - rowserrcheck
    - sqlclosecheck
    - nilerr
    - nilnil
    
    # Best practices
    - dupl
    - goconst
    - gocritic
    - godot
    - gomnd
    - misspell
    - nakedret
    - nolintlint
    - exportloopref
    - exhaustive
    - wrapcheck
    
    # Testing
    - testpackage
    - tparallel
    
    # Formatting
    - lll
    - interfacer
    
  disable:
    - maligned  # deprecated
    - scopelint # deprecated
    - interfacer # deprecated
    - golint    # deprecated, replaced by revive
    - varcheck  # deprecated
    - deadcode  # deprecated
    - structcheck # deprecated

  # Enable all available linters
  # enable-all: true
  # disable:
  #   - linters-to-disable

  # Disable specific linters
  # disable:
  #   - errcheck

  # Enable only specific linters
  # enable:
  #   - megacheck
  #   - govet

  # Enable presets
  # presets:
  #   - bugs
  #   - unused
  #   - complexity
  #   - style
  #   - performance

issues:
  # List of regexps of issue texts to exclude
  exclude:
    # Exclude some linters from running on tests files
    - "G404: Use of weak random number generator"  # Often acceptable in tests
    - "G101: Potential hardcoded credentials"      # Often false positives in tests
    
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocyclo
        - gocognit
        - dupl
        - lll
        - gosec
        - goconst
        
    # Exclude some linters from running on example files
    - path: examples/
      linters:
        - gomnd
        - goconst
        - gosec
        
    # Exclude some linters from running on cmd files (CLI interface)
    - path: cmd/
      linters:
        - lll
        - funlen
        
    # Exclude some linters from running on main.go
    - path: main\.go
      linters:
        - gomnd
        
    # Exclude specific rules
    - text: "weak cryptographic primitive"
      linters:
        - gosec
        
    # Exclude shadow checking on err variables
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
        
    # Exclude certain gocritic checks
    - text: "(commentedOutCode|importShadow)"
      linters:
        - gocritic
        
  # Independently from option `exclude` we use default exclude patterns
  exclude-use-default: false
  
  # Show only new issues: if there are unstaged changes or untracked files,
  # only those changes are analyzed, else only changes in HEAD~ are analyzed
  new: false
  
  # Show only new issues created after git revision `REV`
  # new-from-rev: REV
  
  # Show only new issues created in git patch with set file path
  # new-from-patch: path/to/patch/file
  
  # Maximum issues count per one linter. Set to 0 to disable
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text. Set to 0 to disable
  max-same-issues: 0

severity:
  # Default value is empty string
  # Set the default severity for issues
  default-severity: error
  
  # The default value is false
  # If set to true severity-rules regular expressions become case sensitive
  case-sensitive: false
  
  # Default value is empty list
  # When a list of severity rules are provided, severity information will be added to lint issues
  rules:
    - linters:
        - dupl
      severity: info
    - linters:
        - gocritic
      severity: warning
    - linters:
        - gosec
      severity: error