# Enterprise Typosentinel Configuration
app:
  name: "typosentinel-enterprise"
  version: "1.0.0"
  environment: "development"
  debug: true
  verbose: true
  log_level: "debug"
  data_dir: "./data"
  temp_dir: "./tmp"
  max_workers: 4

server:
  host: "localhost"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  shutdown_timeout: "10s"
  tls:
    enabled: false
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE"]
    allowed_headers: ["*"]
    max_age: 3600

database:
  type: "sqlite"
  database: "./data/typosentinel.db"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "1h"
  migrations_path: "./migrations"

redis:
  enabled: false
  host: "localhost"
  port: 6379
  database: 0
  pool_size: 10
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  idle_timeout: "5m"
  ttl: "1h"

logging:
  level: "debug"
  format: "json"
  output: "stdout"
  max_size: 100
  max_backups: 3
  max_age: 30
  compress: true

metrics:
  enabled: true
  provider: "prometheus"
  address: "localhost:9090"
  namespace: "typosentinel"
  interval: "30s"
  buckets: [0.1, 0.5, 1.0, 2.5, 5.0, 10.0]

security:
  jwt:
    enabled: false
  api_keys:
    enabled: false
  encryption:
    key: "abcdefghijklmnopqrstuvwxyz123456"
    algorithm: "aes-256-gcm"
  password_policy:
    min_length: 8
    require_upper: true
    require_lower: true
    require_digit: true
    require_symbol: false
  csrf:
    enabled: false

ml:
  enabled: true
  model_path: "./models/typo_detection.pb"
  threshold: 0.8
  batch_size: 32
  timeout: "30s"
  cache_size: 1000
  update_interval: "24h"
  model_config:
    enabled: true
    threshold: 0.8
    type: "tensorflow"
    version: "1.0"
    preprocessing:
      normalization: true
      scaling: "standard"
      feature_selection: false
      custom_steps: []
    postprocessing:
      threshold_adjustment: false
      calibration: false
      custom_steps: []

api:
  prefix: "/api"
  version: "v1"
  documentation:
    enabled: true
    path: "/docs"
    title: "Typosentinel API"
    version: "1.0.0"
  rest:
    enabled: true
    host: "localhost"
    port: 8080
    base_path: "/api"
    prefix: "/v1"
    version: "v1"
    versioning:
      enabled: true
      strategy: "path"
      default_version: "v1"
      supported_versions: ["v1"]
    max_body_size: 10485760
    cors:
      enabled: true
      allowed_origins: ["*"]
      allowed_methods: ["GET", "POST", "PUT", "DELETE"]
      allowed_headers: ["*"]
      max_age: 3600
    rate_limiting:
      enabled: true
      rps: 100
      burst: 200
      window: "1m"
      global:
        enabled: true
        rps: 1000
        requests_per_second: 1000
        burst: 2000
        burst_size: 2000
    authentication:
      enabled: false
      method: "jwt"
      methods: ["jwt"]
      jwt:
        enabled: false
      basic_auth:
        users: {}
    documentation:
      enabled: true
      path: "/docs"
      title: "Typosentinel API"
      version: "1.0.0"
  rate_limit:
    enabled: true
    rps: 100
    burst: 200
    window: "1m"
    global:
      enabled: true
      rps: 1000
      requests_per_second: 1000
      burst: 2000
      burst_size: 2000
  auth:
    enabled: false
    method: "jwt"
    methods: ["jwt"]
    jwt:
      enabled: false
    basic_auth:
      users: {}

rate_limit:
  enabled: true
  requests: 100
  window: "1m"
  burst: 200
  skip_paths: ["/health", "/metrics"]
  headers: true

typo_detection:
  enabled: true
  threshold: 0.8
  similarity_threshold: 0.7
  edit_distance_threshold: 2
  max_distance: 2
  phonetic_matching: true
  check_similar_names: true
  check_homoglyphs: true
  dictionary_path: "./dictionaries/common.txt"

registries:
  npm:
    enabled: true
    url: "https://registry.npmjs.org"
    timeout: "30s"
  pypi:
    enabled: true
    url: "https://pypi.org"
    timeout: "30s"
  maven:
    enabled: true
    url: "https://repo1.maven.org/maven2"
    timeout: "30s"
  nuget:
    enabled: true
    url: "https://api.nuget.org/v3/index.json"
    timeout: "30s"
  rubygems:
    enabled: true
    url: "https://rubygems.org"
    timeout: "30s"
  go:
    enabled: true
    url: "https://proxy.golang.org"
    timeout: "30s"
  cargo:
    enabled: true
    url: "https://crates.io"
    timeout: "30s"
  packagist:
    enabled: true
    url: "https://packagist.org"
    timeout: "30s"
  private:
    namespaces: []

ml_analysis:
  enabled: true
  model_path: "./models/ml_analysis.pb"
  threshold: 0.8
  similarity_threshold: 0.7
  malicious_threshold: 0.9
  reputation_threshold: 0.6
  batch_size: 10
  max_features: 100
  timeout: "30s"
  cache_embeddings: true
  parallel_processing: false
  gpu_acceleration: false
  feature_store:
    enabled: true
    provider: "redis"
    connection: "redis://localhost:6379/0"
    ttl: "1h"
  model_updates:
    enabled: true
    interval: "24h"
    source: "./models/updates"
    auto_apply: false

features:
  ml_scoring: true
  advanced_metrics: true
  caching: true
  async_processing: true
  webhooks: false
  bulk_scanning: true
  historical_data: true
  experimental_apis: false

policies:
  fail_on_threats: true
  min_threat_level: "medium"