# Supply Chain Firewall Action
# Reusable GitHub Action for Supply Chain Security

name: 'Supply Chain Firewall'
description: 'Block builds that contain supply chain security risks and policy violations'

inputs:
  package-file:
    description: 'Package file to scan (package.json, requirements.txt, etc.)'
    required: false
    default: 'auto-detect'
  policy-threshold:
    description: 'Policy enforcement threshold (block, alert, review)'
    required: false
    default: 'block'
  asset-criticality:
    description: 'Asset criticality level (PUBLIC, INTERNAL, CRITICAL)'
    required: false
    default: 'INTERNAL'
  fail-on-violation:
    description: 'Fail the build on policy violations'
    required: false
    default: 'true'
  typosentinel-version:
    description: 'Version of Typosentinel to use'
    required: false
    default: 'latest'

outputs:
  risk-score:
    description: 'Overall risk score from the analysis'
  policy-action:
    description: 'Policy action taken (ALLOWED, BLOCKED, ALERT, REVIEW)'
  violations-found:
    description: 'Number of policy violations found'
  analysis-complete:
    description: 'Whether the analysis completed successfully'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        
    - name: Build Typosentinel
      shell: bash
      run: |
        go build -o /usr/local/bin/typosentinel .
        
    - name: Detect package files
      id: detect
      shell: bash
      run: |
        PACKAGE_FILES=""
        if [ "${{ inputs.package-file }}" = "auto-detect" ]; then
          # Auto-detect package files
          if [ -f "package.json" ]; then
            PACKAGE_FILES="package.json"
          elif [ -f "requirements.txt" ]; then
            PACKAGE_FILES="requirements.txt"
          elif [ -f "go.mod" ]; then
            PACKAGE_FILES="go.mod"
          elif [ -f "pom.xml" ]; then
            PACKAGE_FILES="pom.xml"
          elif [ -f "Cargo.toml" ]; then
            PACKAGE_FILES="Cargo.toml"
          elif [ -f "composer.json" ]; then
            PACKAGE_FILES="composer.json"
          elif [ -f "Gemfile" ]; then
            PACKAGE_FILES="Gemfile"
          else
            echo "No package file detected"
            exit 1
          fi
        else
          PACKAGE_FILES="${{ inputs.package-file }}"
        fi
        echo "package-files=$PACKAGE_FILES" >> $GITHUB_OUTPUT
        echo "Detected package files: $PACKAGE_FILES"
        
    - name: Run supply chain analysis
      id: analysis
      shell: bash
      run: |
        typosentinel scan . --output json --supply-chain --advanced 2>/dev/null | tee scan-result.json >/dev/null || echo '{}' > scan-result.json

        THREATS=$(jq '.Threats | length // 0' scan-result.json 2>/dev/null || echo 0)
        TOTAL=$(jq '.TotalPackages // 0' scan-result.json 2>/dev/null || echo 0)
        if [ "$TOTAL" -gt 0 ]; then
          RISK_SCORE=$(echo "$THREATS / $TOTAL" | bc -l)
        else
          RISK_SCORE=0
        fi
        echo "risk-score=$RISK_SCORE" >> $GITHUB_OUTPUT

        POLICY_ACTION="ALLOWED"
        VIOLATIONS_FOUND=0
        if (( $(echo "$THREATS >= 1" | bc -l) )); then
          case "${{ inputs.policy-threshold }}" in
            block)
              POLICY_ACTION="BLOCKED";
              ;;
            alert)
              POLICY_ACTION="ALERT";
              ;;
            review)
              POLICY_ACTION="REVIEW";
              ;;
            *)
              POLICY_ACTION="ALERT";
              ;;
          esac
          VIOLATIONS_FOUND=$THREATS
        fi
        echo "policy-action=$POLICY_ACTION" >> $GITHUB_OUTPUT
        echo "violations-found=$VIOLATIONS_FOUND" >> $GITHUB_OUTPUT
        echo "analysis-complete=true" >> $GITHUB_OUTPUT
        
    - name: Upload analysis results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: supply-chain-analysis
        path: |
          scan-result.json
          
    - name: Enforce policy decision
      if: ${{ inputs.fail-on-violation == 'true' && steps.analysis.outputs.policy-action == 'BLOCKED' }}
      shell: bash
      run: |
        echo "❌ Build blocked by supply chain firewall"
        echo "Policy violation detected with risk score: ${{ steps.analysis.outputs.risk-score }}"
        echo "Policy action: ${{ steps.analysis.outputs.policy-action }}"
        echo ""
        echo "This build has been blocked to prevent potential supply chain attacks."
        echo "Please review the analysis results and address the identified risks."
        exit 1
